// <auto-generated />
using System;
using BSATask.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BSATask.DAL.Migrations
{
    [DbContext(typeof(BSATaskContext))]
    [Migration("20230719133516_UserWithProjects")]
    partial class UserWithProjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BASTask.DAL.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TeamId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 7,
                            CreatedAt = new DateTime(2016, 12, 22, 20, 32, 9, 433, DateTimeKind.Utc).AddTicks(1252),
                            Deadline = new DateTime(9508, 4, 12, 13, 20, 7, 544, DateTimeKind.Utc).AddTicks(6372),
                            Description = "qui",
                            Name = "Lexie Schaefer",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 8,
                            CreatedAt = new DateTime(2013, 11, 23, 1, 20, 56, 63, DateTimeKind.Utc).AddTicks(1767),
                            Deadline = new DateTime(7376, 7, 1, 1, 39, 23, 53, DateTimeKind.Utc).AddTicks(9878),
                            Description = "Ipsum perspiciatis voluptatum et.",
                            Name = "Giuseppe D'Amore",
                            TeamId = 18
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2022, 3, 3, 16, 54, 37, 810, DateTimeKind.Utc).AddTicks(8495),
                            Deadline = new DateTime(8928, 6, 30, 13, 17, 27, 565, DateTimeKind.Utc).AddTicks(9228),
                            Description = "Quidem veniam iure aliquam sequi cumque.",
                            Name = "Alexis Block",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 14,
                            CreatedAt = new DateTime(2017, 11, 24, 11, 47, 45, 895, DateTimeKind.Utc).AddTicks(2989),
                            Deadline = new DateTime(4523, 10, 19, 16, 41, 17, 614, DateTimeKind.Utc).AddTicks(7866),
                            Description = "Ea est nam ea qui reiciendis consectetur est iure.",
                            Name = "Ramon Stark",
                            TeamId = 20
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 6,
                            CreatedAt = new DateTime(2014, 9, 5, 2, 34, 17, 22, DateTimeKind.Utc).AddTicks(9169),
                            Deadline = new DateTime(5775, 10, 13, 0, 23, 59, 954, DateTimeKind.Utc).AddTicks(1460),
                            Description = "Cumque vitae dolor et in possimus.\nUllam voluptas sed rerum est nulla nostrum dolores aut.\nEt et et ut aperiam aperiam libero pariatur.",
                            Name = "Al Jones",
                            TeamId = 16
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 16,
                            CreatedAt = new DateTime(2022, 11, 4, 1, 19, 2, 949, DateTimeKind.Utc).AddTicks(5140),
                            Deadline = new DateTime(5461, 3, 29, 19, 9, 29, 283, DateTimeKind.Utc).AddTicks(3287),
                            Description = "Rerum enim in minima. Deserunt atque odio ipsa modi corporis voluptatem. Rem rerum autem officiis rerum et similique quam eveniet. Tempora dolorum dicta exercitationem ea dicta est aut nemo dolorem.",
                            Name = "Raquel O'Conner",
                            TeamId = 14
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 14,
                            CreatedAt = new DateTime(2022, 4, 21, 6, 4, 45, 202, DateTimeKind.Utc).AddTicks(941),
                            Deadline = new DateTime(9748, 8, 11, 14, 44, 5, 440, DateTimeKind.Utc).AddTicks(8177),
                            Description = "Repellat dolorem eum.",
                            Name = "Brett Gaylord",
                            TeamId = 20
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 8,
                            CreatedAt = new DateTime(2018, 10, 16, 3, 35, 9, 971, DateTimeKind.Utc).AddTicks(1312),
                            Deadline = new DateTime(9398, 12, 29, 7, 49, 3, 254, DateTimeKind.Utc).AddTicks(6669),
                            Description = "Quas quis in molestiae ut.\nQui nisi provident qui nesciunt aut eligendi recusandae.\nPorro autem a beatae ullam recusandae qui.\nConsequatur voluptas repudiandae quisquam.",
                            Name = "Concepcion Grady",
                            TeamId = 12
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 9,
                            CreatedAt = new DateTime(2015, 12, 8, 21, 26, 19, 813, DateTimeKind.Utc).AddTicks(8653),
                            Deadline = new DateTime(2072, 9, 10, 19, 58, 33, 751, DateTimeKind.Utc).AddTicks(1351),
                            Description = "Nesciunt sit velit eius.\nDeleniti perferendis aut qui voluptas in dolore ex nemo sunt.\nConsequatur sed animi quisquam qui et qui soluta nostrum.\nId ea quia quia.",
                            Name = "Carson Koelpin",
                            TeamId = 17
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 17,
                            CreatedAt = new DateTime(2014, 4, 6, 10, 5, 31, 711, DateTimeKind.Utc).AddTicks(5432),
                            Deadline = new DateTime(6631, 3, 3, 11, 57, 47, 799, DateTimeKind.Utc).AddTicks(3239),
                            Description = "doloremque",
                            Name = "Enoch Brekke",
                            TeamId = 11
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 8,
                            CreatedAt = new DateTime(2022, 1, 9, 0, 47, 53, 655, DateTimeKind.Utc).AddTicks(5480),
                            Deadline = new DateTime(2588, 11, 22, 17, 31, 53, 415, DateTimeKind.Utc).AddTicks(3905),
                            Description = "Voluptatem exercitationem et labore occaecati nihil quae minima provident.\nPerspiciatis error repudiandae.\nEst incidunt modi sit ea.\nTempore eaque libero architecto sit temporibus explicabo numquam.\nRem explicabo dignissimos vitae.\nAutem et consectetur fugiat.",
                            Name = "Emile Waters",
                            TeamId = 11
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 17,
                            CreatedAt = new DateTime(2020, 3, 16, 7, 54, 57, 744, DateTimeKind.Utc).AddTicks(3161),
                            Deadline = new DateTime(5903, 12, 30, 0, 32, 10, 198, DateTimeKind.Utc).AddTicks(5149),
                            Description = "nam",
                            Name = "Maryse Kirlin",
                            TeamId = 11
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 11,
                            CreatedAt = new DateTime(2023, 2, 22, 0, 52, 2, 76, DateTimeKind.Utc).AddTicks(7858),
                            Deadline = new DateTime(2246, 3, 20, 13, 17, 54, 52, DateTimeKind.Utc).AddTicks(6481),
                            Description = "Soluta voluptatem modi non.",
                            Name = "Kitty Feest",
                            TeamId = 17
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 18,
                            CreatedAt = new DateTime(2020, 10, 18, 17, 31, 49, 693, DateTimeKind.Utc).AddTicks(3859),
                            Deadline = new DateTime(7935, 1, 7, 11, 22, 5, 749, DateTimeKind.Utc).AddTicks(2519),
                            Description = "Sed autem consectetur voluptate illo expedita excepturi.\nIllo voluptas et aliquid amet consequatur eveniet.\nVoluptas aliquam quo blanditiis in cumque maiores.",
                            Name = "Eileen Hirthe",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2022, 5, 27, 21, 3, 2, 716, DateTimeKind.Utc).AddTicks(1593),
                            Deadline = new DateTime(3981, 8, 12, 6, 45, 19, 944, DateTimeKind.Utc).AddTicks(9709),
                            Description = "Quae quos tenetur omnis atque odit sequi sed voluptatem doloremque.\nRecusandae quasi maxime et placeat odit vero eaque sit ex.\nAlias debitis mollitia provident quia impedit est.\nId officia dolorum ut.",
                            Name = "Guadalupe Tillman",
                            TeamId = 18
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 7,
                            CreatedAt = new DateTime(2016, 4, 14, 10, 35, 4, 573, DateTimeKind.Utc).AddTicks(7095),
                            Deadline = new DateTime(7909, 3, 28, 14, 49, 9, 695, DateTimeKind.Utc).AddTicks(8441),
                            Description = "Provident dolores pariatur consequuntur dolorem est.\nVoluptas ullam facere et inventore aut consequatur ut.\nVoluptatum qui vel ea quasi occaecati odio.\nDolorem sit laboriosam non corporis.\nOccaecati eos autem odio.\nEligendi ipsa maxime labore eaque est.",
                            Name = "Creola Schowalter",
                            TeamId = 19
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 4,
                            CreatedAt = new DateTime(2018, 3, 21, 0, 55, 13, 755, DateTimeKind.Utc).AddTicks(7220),
                            Deadline = new DateTime(2108, 9, 11, 3, 32, 28, 765, DateTimeKind.Utc).AddTicks(1826),
                            Description = "Cum ut consectetur cupiditate quia velit. Ducimus est incidunt non consequatur nihil. Reiciendis aut non beatae assumenda quasi quae blanditiis.",
                            Name = "Nona Pacocha",
                            TeamId = 13
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 8,
                            CreatedAt = new DateTime(2020, 4, 6, 8, 53, 27, 809, DateTimeKind.Utc).AddTicks(4876),
                            Deadline = new DateTime(4839, 5, 28, 2, 12, 44, 610, DateTimeKind.Utc).AddTicks(6583),
                            Description = "Consequuntur quo incidunt animi fuga et officia voluptates qui. Est ut et et vel qui quod veniam. Inventore rerum inventore et officiis quidem nemo mollitia laborum voluptatem. Corrupti earum alias soluta non et culpa. Ut maxime exercitationem explicabo et vitae qui nesciunt.",
                            Name = "Dee Schiller",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 9,
                            CreatedAt = new DateTime(2015, 4, 23, 0, 15, 32, 561, DateTimeKind.Utc).AddTicks(4358),
                            Deadline = new DateTime(8159, 3, 1, 8, 59, 4, 97, DateTimeKind.Utc).AddTicks(5166),
                            Description = "Ea qui fugit atque. Beatae at dolorem soluta qui nihil sequi. Ipsum aperiam porro.",
                            Name = "Eliezer Miller",
                            TeamId = 11
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 19,
                            CreatedAt = new DateTime(2021, 12, 11, 2, 47, 29, 895, DateTimeKind.Utc).AddTicks(5295),
                            Deadline = new DateTime(7067, 5, 20, 19, 27, 25, 641, DateTimeKind.Utc).AddTicks(2050),
                            Description = "Dolorum quaerat molestiae at voluptate aut velit consequatur veniam quia. Quaerat fuga magni voluptates deleniti. Et rem nesciunt ea non quis odio. Magni quis quia laboriosam nam assumenda iusto voluptas ut. Rerum fuga nobis quis consequatur esse. Non sapiente fuga.",
                            Name = "Jacynthe Batz",
                            TeamId = 17
                        });
                });

            modelBuilder.Entity("BASTask.DAL.Entities.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerformerId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerformerId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2015, 12, 19, 22, 58, 54, 61, DateTimeKind.Utc).AddTicks(7482),
                            Description = "libero",
                            FinishedAt = new DateTime(8109, 3, 18, 15, 17, 41, 169, DateTimeKind.Utc).AddTicks(5271),
                            Name = "Isobel King",
                            PerformerId = 12,
                            ProjectId = 5,
                            State = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2017, 3, 27, 22, 3, 48, 838, DateTimeKind.Utc).AddTicks(8445),
                            Description = "esse",
                            FinishedAt = new DateTime(5333, 12, 9, 12, 22, 2, 690, DateTimeKind.Utc).AddTicks(5672),
                            Name = "Mac Herman",
                            PerformerId = 20,
                            ProjectId = 16,
                            State = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 3, 9, 1, 1, 55, 427, DateTimeKind.Utc).AddTicks(4158),
                            Description = "Inventore qui quas accusantium sunt eum ab.",
                            FinishedAt = new DateTime(7315, 3, 21, 2, 31, 29, 966, DateTimeKind.Utc).AddTicks(7167),
                            Name = "Desmond Casper",
                            PerformerId = 15,
                            ProjectId = 20,
                            State = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2018, 12, 17, 16, 22, 8, 247, DateTimeKind.Utc).AddTicks(1280),
                            Description = "consequatur",
                            FinishedAt = new DateTime(3345, 2, 9, 11, 54, 8, 111, DateTimeKind.Utc).AddTicks(9405),
                            Name = "Amie Littel",
                            PerformerId = 3,
                            ProjectId = 9,
                            State = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2018, 11, 13, 11, 20, 59, 993, DateTimeKind.Utc).AddTicks(1969),
                            Description = "Sint quisquam impedit laborum qui tempore qui delectus reiciendis. Perspiciatis tempora quasi voluptatem rerum porro rerum dolores recusandae ipsa. Id ipsa consequatur consequuntur quidem illum voluptas.",
                            FinishedAt = new DateTime(4140, 6, 12, 6, 56, 34, 984, DateTimeKind.Utc).AddTicks(9898),
                            Name = "Augustus Kilback",
                            PerformerId = 9,
                            ProjectId = 19,
                            State = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2017, 12, 29, 8, 21, 24, 234, DateTimeKind.Utc).AddTicks(5226),
                            Description = "Voluptas autem velit dolorem. Omnis quia doloribus quidem voluptatem enim. Itaque deleniti necessitatibus aliquid sunt eaque numquam voluptates occaecati. Non ratione ratione sit incidunt.",
                            FinishedAt = new DateTime(6190, 5, 18, 16, 24, 30, 152, DateTimeKind.Utc).AddTicks(9435),
                            Name = "Dan Windler",
                            PerformerId = 17,
                            ProjectId = 20,
                            State = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2018, 10, 4, 14, 52, 50, 503, DateTimeKind.Utc).AddTicks(4189),
                            Description = "Tenetur numquam quas inventore recusandae dolore laboriosam excepturi unde.\nVitae ex magni non autem nulla expedita ut.\nSit numquam repudiandae.\nUnde dolor amet qui molestiae temporibus sed dolorum est.",
                            FinishedAt = new DateTime(6346, 2, 28, 7, 57, 41, 78, DateTimeKind.Utc).AddTicks(6202),
                            Name = "Godfrey Halvorson",
                            PerformerId = 7,
                            ProjectId = 3,
                            State = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2015, 5, 30, 1, 50, 32, 526, DateTimeKind.Utc).AddTicks(2022),
                            Description = "Consequatur quis commodi.",
                            FinishedAt = new DateTime(9838, 12, 27, 6, 19, 40, 219, DateTimeKind.Utc).AddTicks(9313),
                            Name = "Rex Aufderhar",
                            PerformerId = 5,
                            ProjectId = 10,
                            State = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2013, 8, 26, 17, 33, 37, 115, DateTimeKind.Utc).AddTicks(288),
                            Description = "Nulla blanditiis architecto alias itaque maxime omnis qui iure sunt. Facere iusto quod velit eos sunt. Aliquam hic hic sed quasi expedita iure quis voluptas. Praesentium ipsa cumque voluptatem harum. Accusantium dolores explicabo tempore cum aperiam iusto.",
                            FinishedAt = new DateTime(7327, 9, 12, 8, 11, 29, 640, DateTimeKind.Utc).AddTicks(7114),
                            Name = "Elijah Walsh",
                            PerformerId = 10,
                            ProjectId = 20,
                            State = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2015, 12, 14, 13, 58, 31, 305, DateTimeKind.Utc).AddTicks(3849),
                            Description = "At et est. Quisquam nam et consequuntur. Pariatur quod dicta occaecati. Ipsa occaecati sapiente recusandae sapiente unde perspiciatis qui. Dicta dolores natus id tempore voluptate impedit consequuntur ipsum voluptatem. Est eum culpa vitae natus magnam quidem ratione porro cumque.",
                            FinishedAt = new DateTime(5911, 11, 10, 1, 44, 43, 421, DateTimeKind.Utc).AddTicks(5411),
                            Name = "Lesley Reichert",
                            PerformerId = 5,
                            ProjectId = 4,
                            State = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 4, 27, 8, 19, 3, 475, DateTimeKind.Utc).AddTicks(640),
                            Description = "Fugiat est molestiae quia quae vel sunt omnis id.\nDolorem atque quia dolores reiciendis quia mollitia.",
                            FinishedAt = new DateTime(2792, 1, 30, 21, 12, 50, 874, DateTimeKind.Utc).AddTicks(426),
                            Name = "Heaven Jones",
                            PerformerId = 17,
                            ProjectId = 1,
                            State = 2
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2020, 7, 7, 15, 56, 56, 702, DateTimeKind.Utc).AddTicks(2981),
                            Description = "Enim nam reprehenderit debitis molestiae voluptas quaerat numquam qui. Sunt ipsa quia. Libero sunt libero nihil. Assumenda saepe occaecati id qui fugiat est.",
                            FinishedAt = new DateTime(3365, 9, 8, 13, 56, 2, 615, DateTimeKind.Utc).AddTicks(6958),
                            Name = "Jonathon Lind",
                            PerformerId = 6,
                            ProjectId = 9,
                            State = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 6, 16, 16, 52, 59, 876, DateTimeKind.Utc).AddTicks(4451),
                            Description = "voluptatem",
                            FinishedAt = new DateTime(9408, 6, 1, 13, 14, 32, 347, DateTimeKind.Utc).AddTicks(9084),
                            Name = "Justice Murphy",
                            PerformerId = 5,
                            ProjectId = 7,
                            State = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 4, 24, 12, 38, 50, 904, DateTimeKind.Utc).AddTicks(741),
                            Description = "Atque et delectus. Nostrum qui illum ipsam amet est illum sapiente doloribus quam. Molestias similique voluptatem provident nisi eos quia. Et veritatis aut architecto omnis blanditiis non numquam. Officia vel qui. Consequatur eligendi quam eveniet.",
                            FinishedAt = new DateTime(3568, 2, 8, 18, 32, 36, 424, DateTimeKind.Utc).AddTicks(7354),
                            Name = "Connie Okuneva",
                            PerformerId = 5,
                            ProjectId = 18,
                            State = 2
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 2, 10, 1, 53, 34, 541, DateTimeKind.Utc).AddTicks(4317),
                            Description = "Quod autem qui autem necessitatibus consequatur quaerat eius et voluptas. Et autem adipisci. Eveniet fugiat nesciunt voluptatem consequuntur omnis. Quam adipisci qui.",
                            FinishedAt = new DateTime(6405, 2, 8, 13, 17, 48, 498, DateTimeKind.Utc).AddTicks(4075),
                            Name = "Dominique Gislason",
                            PerformerId = 18,
                            ProjectId = 7,
                            State = 0
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2014, 4, 29, 20, 14, 17, 30, DateTimeKind.Utc).AddTicks(8810),
                            Description = "Natus fugit ea neque necessitatibus.",
                            FinishedAt = new DateTime(4938, 11, 30, 12, 32, 34, 139, DateTimeKind.Utc).AddTicks(2409),
                            Name = "Susanna Murphy",
                            PerformerId = 17,
                            ProjectId = 3,
                            State = 2
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 5, 18, 9, 4, 51, 220, DateTimeKind.Utc).AddTicks(3095),
                            Description = "distinctio",
                            FinishedAt = new DateTime(5853, 12, 25, 23, 53, 48, 265, DateTimeKind.Utc).AddTicks(5462),
                            Name = "Jefferey Casper",
                            PerformerId = 15,
                            ProjectId = 14,
                            State = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 3, 15, 8, 38, 53, 157, DateTimeKind.Utc).AddTicks(6182),
                            Description = "At voluptate et eveniet corporis inventore nihil. Aut aut quia assumenda. Eius quasi natus consequatur dolores assumenda et. Quia officiis ut aliquid veniam inventore odio.",
                            FinishedAt = new DateTime(9847, 11, 23, 23, 41, 39, 606, DateTimeKind.Utc).AddTicks(4235),
                            Name = "Janet Daniel",
                            PerformerId = 19,
                            ProjectId = 8,
                            State = 0
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 7, 11, 7, 21, 10, 133, DateTimeKind.Utc).AddTicks(1850),
                            Description = "Ipsum laborum officia hic ratione sunt natus ullam.\nEst iste sed alias ut tempora.\nNostrum nemo qui id.\nQuia pariatur eos deserunt.",
                            FinishedAt = new DateTime(4804, 5, 5, 13, 58, 59, 217, DateTimeKind.Utc).AddTicks(2816),
                            Name = "Kelsie Prohaska",
                            PerformerId = 13,
                            ProjectId = 1,
                            State = 2
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2020, 10, 29, 17, 37, 50, 944, DateTimeKind.Utc).AddTicks(4448),
                            Description = "quas",
                            FinishedAt = new DateTime(5588, 7, 26, 3, 54, 34, 304, DateTimeKind.Utc).AddTicks(7524),
                            Name = "Casey Frami",
                            PerformerId = 16,
                            ProjectId = 19,
                            State = 2
                        });
                });

            modelBuilder.Entity("BASTask.DAL.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 5, 31, 15, 28, 17, 317, DateTimeKind.Utc).AddTicks(8091),
                            Name = "Christiana Cronin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2017, 4, 23, 6, 37, 31, 754, DateTimeKind.Utc).AddTicks(2037),
                            Name = "Vernice Doyle"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 2, 5, 20, 10, 55, 872, DateTimeKind.Utc).AddTicks(8573),
                            Name = "Rafael Jerde"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2018, 11, 25, 13, 16, 6, 321, DateTimeKind.Utc).AddTicks(9765),
                            Name = "Harold Koelpin"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2016, 9, 19, 19, 6, 48, 300, DateTimeKind.Utc).AddTicks(2305),
                            Name = "Myrtie Carter"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2015, 11, 18, 3, 50, 14, 338, DateTimeKind.Utc).AddTicks(7485),
                            Name = "Matilde Wilderman"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2015, 9, 8, 8, 17, 25, 485, DateTimeKind.Utc).AddTicks(2914),
                            Name = "Macy Luettgen"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2014, 8, 6, 19, 29, 30, 246, DateTimeKind.Utc).AddTicks(4721),
                            Name = "Alexandrea McGlynn"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 5, 17, 12, 58, 1, 52, DateTimeKind.Utc).AddTicks(7921),
                            Name = "Jefferey Leffler"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 6, 15, 17, 50, 10, 326, DateTimeKind.Utc).AddTicks(9314),
                            Name = "Antonina Lang"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2017, 8, 20, 11, 56, 53, 146, DateTimeKind.Utc).AddTicks(1109),
                            Name = "Raymundo Tremblay"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2015, 12, 14, 10, 25, 29, 56, DateTimeKind.Utc).AddTicks(8084),
                            Name = "Else Wunsch"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2018, 10, 21, 1, 32, 4, 363, DateTimeKind.Utc).AddTicks(3400),
                            Name = "Amely Wehner"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2015, 2, 7, 20, 37, 34, 222, DateTimeKind.Utc).AddTicks(3524),
                            Name = "Albina Metz"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2017, 4, 19, 23, 48, 7, 930, DateTimeKind.Utc).AddTicks(8937),
                            Name = "Jeffrey Harber"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2022, 4, 1, 14, 49, 57, 891, DateTimeKind.Utc).AddTicks(1186),
                            Name = "Daryl Gusikowski"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2014, 11, 26, 0, 40, 52, 256, DateTimeKind.Utc).AddTicks(7583),
                            Name = "Genesis Herman"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2014, 1, 7, 8, 22, 26, 899, DateTimeKind.Utc).AddTicks(73),
                            Name = "Barton Witting"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2017, 12, 2, 13, 7, 37, 99, DateTimeKind.Utc).AddTicks(8754),
                            Name = "Timmy Lemke"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 5, 17, 16, 40, 43, 882, DateTimeKind.Utc).AddTicks(6663),
                            Name = "Kenny Wolff"
                        });
                });

            modelBuilder.Entity("BASTask.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDay = new DateTime(2015, 12, 11, 15, 48, 27, 267, DateTimeKind.Utc).AddTicks(7529),
                            Email = "Erna_Kovacek@gmail.com",
                            FirstName = "Braden",
                            LastName = "Kuhlman",
                            RegisteredAt = new DateTime(2014, 2, 24, 2, 44, 29, 127, DateTimeKind.Utc).AddTicks(5696),
                            TeamId = 9
                        },
                        new
                        {
                            Id = 2,
                            BirthDay = new DateTime(2020, 8, 3, 6, 59, 24, 211, DateTimeKind.Utc).AddTicks(2446),
                            Email = "Nella_Collins@yahoo.com",
                            FirstName = "Shaylee",
                            LastName = "Wuckert",
                            RegisteredAt = new DateTime(2016, 1, 14, 21, 36, 52, 731, DateTimeKind.Utc).AddTicks(5573),
                            TeamId = 18
                        },
                        new
                        {
                            Id = 3,
                            BirthDay = new DateTime(2021, 4, 25, 2, 33, 12, 659, DateTimeKind.Utc).AddTicks(9275),
                            Email = "Lydia32@gmail.com",
                            FirstName = "Iliana",
                            LastName = "Cummings",
                            RegisteredAt = new DateTime(2022, 10, 25, 18, 50, 2, 570, DateTimeKind.Utc).AddTicks(2647),
                            TeamId = 4
                        },
                        new
                        {
                            Id = 4,
                            BirthDay = new DateTime(2009, 1, 31, 9, 40, 0, 85, DateTimeKind.Utc).AddTicks(1189),
                            Email = "Abagail_Hermiston54@hotmail.com",
                            FirstName = "Vernice",
                            LastName = "Walter",
                            RegisteredAt = new DateTime(2017, 5, 7, 10, 55, 46, 186, DateTimeKind.Utc).AddTicks(2796),
                            TeamId = 13
                        },
                        new
                        {
                            Id = 5,
                            BirthDay = new DateTime(2010, 12, 12, 11, 53, 4, 379, DateTimeKind.Utc).AddTicks(9277),
                            Email = "Albert.Kling@gmail.com",
                            FirstName = "Alize",
                            LastName = "Quitzon",
                            RegisteredAt = new DateTime(2018, 1, 28, 0, 25, 48, 641, DateTimeKind.Utc).AddTicks(7389),
                            TeamId = 10
                        },
                        new
                        {
                            Id = 6,
                            BirthDay = new DateTime(2018, 9, 3, 18, 51, 23, 429, DateTimeKind.Utc).AddTicks(412),
                            Email = "Gillian_Mitchell65@yahoo.com",
                            FirstName = "Libbie",
                            LastName = "Ratke",
                            RegisteredAt = new DateTime(2014, 10, 13, 8, 3, 53, 581, DateTimeKind.Utc).AddTicks(8924),
                            TeamId = 18
                        },
                        new
                        {
                            Id = 7,
                            BirthDay = new DateTime(2018, 7, 24, 7, 8, 15, 650, DateTimeKind.Utc).AddTicks(7415),
                            Email = "Serena73@yahoo.com",
                            FirstName = "Maudie",
                            LastName = "Heller",
                            RegisteredAt = new DateTime(2023, 7, 8, 13, 50, 54, 72, DateTimeKind.Utc).AddTicks(9108),
                            TeamId = 17
                        },
                        new
                        {
                            Id = 8,
                            BirthDay = new DateTime(2008, 8, 13, 6, 56, 38, 873, DateTimeKind.Utc).AddTicks(8021),
                            Email = "Camron_Kutch@hotmail.com",
                            FirstName = "Deborah",
                            LastName = "Hand",
                            RegisteredAt = new DateTime(2018, 2, 24, 14, 28, 2, 500, DateTimeKind.Utc).AddTicks(3156),
                            TeamId = 14
                        },
                        new
                        {
                            Id = 9,
                            BirthDay = new DateTime(2004, 6, 5, 9, 27, 8, 62, DateTimeKind.Utc).AddTicks(5059),
                            Email = "Kelley_Ernser90@yahoo.com",
                            FirstName = "Kameron",
                            LastName = "Reichel",
                            RegisteredAt = new DateTime(2017, 4, 19, 16, 11, 0, 241, DateTimeKind.Utc).AddTicks(2583),
                            TeamId = 11
                        },
                        new
                        {
                            Id = 10,
                            BirthDay = new DateTime(2011, 10, 16, 8, 3, 5, 103, DateTimeKind.Utc).AddTicks(6684),
                            Email = "Nettie.Lind@hotmail.com",
                            FirstName = "Lenny",
                            LastName = "Ward",
                            RegisteredAt = new DateTime(2018, 5, 10, 7, 57, 6, 111, DateTimeKind.Utc).AddTicks(4685),
                            TeamId = 9
                        },
                        new
                        {
                            Id = 11,
                            BirthDay = new DateTime(1995, 8, 5, 20, 14, 25, 388, DateTimeKind.Utc).AddTicks(2211),
                            Email = "Ray31@yahoo.com",
                            FirstName = "Torey",
                            LastName = "Stokes",
                            RegisteredAt = new DateTime(2021, 4, 23, 8, 42, 9, 32, DateTimeKind.Utc).AddTicks(3785),
                            TeamId = 5
                        },
                        new
                        {
                            Id = 12,
                            BirthDay = new DateTime(2000, 6, 29, 11, 23, 14, 627, DateTimeKind.Utc).AddTicks(1792),
                            Email = "Chasity.Johnston97@gmail.com",
                            FirstName = "Gino",
                            LastName = "Kilback",
                            RegisteredAt = new DateTime(2017, 1, 13, 1, 11, 41, 611, DateTimeKind.Utc).AddTicks(8108),
                            TeamId = 15
                        },
                        new
                        {
                            Id = 13,
                            BirthDay = new DateTime(2020, 2, 11, 5, 49, 1, 669, DateTimeKind.Utc).AddTicks(2238),
                            Email = "Felicity54@gmail.com",
                            FirstName = "Ladarius",
                            LastName = "Trantow",
                            RegisteredAt = new DateTime(2023, 2, 18, 5, 59, 31, 542, DateTimeKind.Utc).AddTicks(6954),
                            TeamId = 5
                        },
                        new
                        {
                            Id = 14,
                            BirthDay = new DateTime(2020, 5, 9, 9, 14, 21, 186, DateTimeKind.Utc).AddTicks(7857),
                            Email = "Shad_Gislason31@yahoo.com",
                            FirstName = "Edyth",
                            LastName = "Emmerich",
                            RegisteredAt = new DateTime(2018, 12, 14, 14, 1, 48, 985, DateTimeKind.Utc).AddTicks(9951),
                            TeamId = 6
                        },
                        new
                        {
                            Id = 15,
                            BirthDay = new DateTime(1994, 11, 6, 3, 25, 51, 569, DateTimeKind.Utc).AddTicks(4331),
                            Email = "Larry_Abernathy@yahoo.com",
                            FirstName = "Evie",
                            LastName = "Gutkowski",
                            RegisteredAt = new DateTime(2015, 5, 18, 2, 18, 24, 534, DateTimeKind.Utc).AddTicks(9089),
                            TeamId = 6
                        },
                        new
                        {
                            Id = 16,
                            BirthDay = new DateTime(2007, 5, 11, 12, 59, 20, 768, DateTimeKind.Utc).AddTicks(6750),
                            Email = "Alisa63@yahoo.com",
                            FirstName = "Nathanial",
                            LastName = "Huel",
                            RegisteredAt = new DateTime(2019, 9, 3, 16, 37, 16, 696, DateTimeKind.Utc).AddTicks(5959),
                            TeamId = 5
                        },
                        new
                        {
                            Id = 17,
                            BirthDay = new DateTime(2005, 5, 19, 4, 47, 1, 169, DateTimeKind.Utc).AddTicks(3200),
                            Email = "Adela32@gmail.com",
                            FirstName = "Nick",
                            LastName = "Weimann",
                            RegisteredAt = new DateTime(2015, 10, 1, 22, 7, 29, 82, DateTimeKind.Utc).AddTicks(5947),
                            TeamId = 3
                        },
                        new
                        {
                            Id = 18,
                            BirthDay = new DateTime(2013, 4, 22, 19, 19, 31, 623, DateTimeKind.Utc).AddTicks(3034),
                            Email = "Geovanny_Gleichner@gmail.com",
                            FirstName = "Maegan",
                            LastName = "Rowe",
                            RegisteredAt = new DateTime(2020, 2, 1, 8, 35, 45, 845, DateTimeKind.Utc).AddTicks(2244),
                            TeamId = 8
                        },
                        new
                        {
                            Id = 19,
                            BirthDay = new DateTime(2023, 5, 2, 12, 22, 19, 390, DateTimeKind.Utc).AddTicks(857),
                            Email = "Randi.Rolfson59@yahoo.com",
                            FirstName = "Pattie",
                            LastName = "Heathcote",
                            RegisteredAt = new DateTime(2018, 5, 29, 3, 28, 17, 149, DateTimeKind.Utc).AddTicks(4997),
                            TeamId = 12
                        },
                        new
                        {
                            Id = 20,
                            BirthDay = new DateTime(2004, 3, 4, 19, 26, 3, 63, DateTimeKind.Utc).AddTicks(9444),
                            Email = "Henry.Jaskolski@gmail.com",
                            FirstName = "Lori",
                            LastName = "Cummerata",
                            RegisteredAt = new DateTime(2022, 2, 3, 18, 6, 28, 995, DateTimeKind.Utc).AddTicks(440),
                            TeamId = 12
                        });
                });

            modelBuilder.Entity("BASTask.DAL.Entities.Project", b =>
                {
                    b.HasOne("BASTask.DAL.Entities.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BASTask.DAL.Entities.Team", "Team")
                        .WithMany("Projects")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BASTask.DAL.Entities.Task", b =>
                {
                    b.HasOne("BASTask.DAL.Entities.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BASTask.DAL.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BASTask.DAL.Entities.User", b =>
                {
                    b.HasOne("BASTask.DAL.Entities.Team", "Team")
                        .WithMany("Users")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BASTask.DAL.Entities.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("BASTask.DAL.Entities.Team", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BASTask.DAL.Entities.User", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
