// <auto-generated />
using System;
using BSATask.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BSATask.DAL.Migrations
{
    [DbContext(typeof(BSATaskContext))]
    [Migration("20230718134555_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BASTask.DAL.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 20,
                            CreatedAt = new DateTime(2017, 9, 19, 20, 53, 6, 112, DateTimeKind.Utc).AddTicks(1854),
                            Deadline = new DateTime(9696, 1, 9, 4, 9, 45, 77, DateTimeKind.Utc).AddTicks(4438),
                            Description = "voluptates",
                            Name = "Wilma Walsh",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2017, 8, 8, 7, 19, 13, 749, DateTimeKind.Utc).AddTicks(6996),
                            Deadline = new DateTime(5095, 5, 6, 6, 24, 1, 991, DateTimeKind.Utc).AddTicks(7441),
                            Description = "Expedita possimus culpa necessitatibus tempore omnis quod ut dignissimos. Beatae est nostrum dolores. Fuga voluptates doloremque alias ut. Aut aut soluta sit. Iste dolor voluptates molestiae fugit ullam doloribus dicta est.",
                            Name = "Lonzo Bednar",
                            TeamId = 18
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2020, 5, 22, 20, 39, 19, 191, DateTimeKind.Utc).AddTicks(3742),
                            Deadline = new DateTime(5718, 10, 2, 17, 41, 31, 833, DateTimeKind.Utc).AddTicks(4676),
                            Description = "Provident ea et voluptates quaerat aut.\nEst dolores ut libero nisi ipsa.\nDolorem ipsam omnis eum fugiat harum possimus qui.\nVoluptatem quae ad soluta eum.\nEa quo maxime exercitationem excepturi eligendi natus expedita.\nDoloremque eveniet ipsa velit quia et suscipit molestias harum.",
                            Name = "Janessa Koch",
                            TeamId = 15
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 11,
                            CreatedAt = new DateTime(2020, 2, 11, 5, 50, 34, 617, DateTimeKind.Utc).AddTicks(2074),
                            Deadline = new DateTime(3758, 4, 7, 5, 50, 13, 957, DateTimeKind.Utc).AddTicks(980),
                            Description = "Molestiae voluptate ut sit doloremque quo odit doloribus.\nEt non amet dolores.",
                            Name = "Mario Anderson",
                            TeamId = 16
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 20,
                            CreatedAt = new DateTime(2017, 12, 3, 3, 29, 55, 443, DateTimeKind.Utc).AddTicks(1622),
                            Deadline = new DateTime(5756, 1, 1, 2, 45, 6, 441, DateTimeKind.Utc).AddTicks(2185),
                            Description = "Placeat deserunt qui aut incidunt veniam voluptatum molestias eos mollitia. Vitae illum blanditiis beatae eligendi consequatur et. Placeat culpa perspiciatis perferendis eius. Delectus doloribus quia repudiandae atque et illo beatae. Aut rerum voluptatem accusamus magnam id vel adipisci doloribus.",
                            Name = "Stevie Hoeger",
                            TeamId = 15
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 12,
                            CreatedAt = new DateTime(2021, 6, 27, 20, 27, 13, 680, DateTimeKind.Utc).AddTicks(4338),
                            Deadline = new DateTime(2203, 3, 28, 11, 39, 44, 980, DateTimeKind.Utc).AddTicks(9065),
                            Description = "Et autem dignissimos voluptatem nemo.",
                            Name = "Elian Weimann",
                            TeamId = 19
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 6,
                            CreatedAt = new DateTime(2019, 9, 20, 1, 42, 5, 904, DateTimeKind.Utc).AddTicks(8722),
                            Deadline = new DateTime(8129, 1, 5, 6, 22, 36, 48, DateTimeKind.Utc).AddTicks(4079),
                            Description = "et",
                            Name = "Cory Kerluke",
                            TeamId = 12
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 19,
                            CreatedAt = new DateTime(2019, 7, 22, 14, 49, 35, 834, DateTimeKind.Utc).AddTicks(3911),
                            Deadline = new DateTime(5885, 3, 31, 6, 56, 26, 454, DateTimeKind.Utc).AddTicks(3050),
                            Description = "Nemo omnis debitis neque exercitationem minus cumque neque.",
                            Name = "Cecelia Torphy",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 4,
                            CreatedAt = new DateTime(2014, 4, 23, 8, 36, 47, 431, DateTimeKind.Utc).AddTicks(1265),
                            Deadline = new DateTime(4607, 5, 27, 19, 42, 29, 626, DateTimeKind.Utc).AddTicks(5085),
                            Description = "et",
                            Name = "Palma Zulauf",
                            TeamId = 12
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 6,
                            CreatedAt = new DateTime(2020, 6, 29, 15, 29, 38, 571, DateTimeKind.Utc).AddTicks(6794),
                            Deadline = new DateTime(2620, 11, 10, 2, 12, 34, 688, DateTimeKind.Utc).AddTicks(3377),
                            Description = "sed",
                            Name = "Pedro Runolfsdottir",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 19,
                            CreatedAt = new DateTime(2021, 2, 28, 5, 40, 34, 664, DateTimeKind.Utc).AddTicks(1083),
                            Deadline = new DateTime(2701, 8, 29, 10, 47, 4, 418, DateTimeKind.Utc).AddTicks(2580),
                            Description = "Laudantium id et cupiditate maxime laboriosam quibusdam magni rerum.",
                            Name = "Carli Gutkowski",
                            TeamId = 18
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 6,
                            CreatedAt = new DateTime(2015, 1, 7, 9, 23, 41, 68, DateTimeKind.Utc).AddTicks(4880),
                            Deadline = new DateTime(5435, 7, 2, 5, 22, 9, 820, DateTimeKind.Utc).AddTicks(6761),
                            Description = "Laboriosam aut voluptas non facilis exercitationem vel.",
                            Name = "Alba Casper",
                            TeamId = 11
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 18,
                            CreatedAt = new DateTime(2018, 7, 5, 21, 5, 44, 176, DateTimeKind.Utc).AddTicks(849),
                            Deadline = new DateTime(4642, 10, 2, 17, 18, 33, 86, DateTimeKind.Utc).AddTicks(4737),
                            Description = "Earum facilis exercitationem excepturi est consequatur maxime tempore illum quia. Cum illo odio molestias quibusdam aliquid et. Consequatur et et sit dolores ipsum ut voluptate.",
                            Name = "Adalberto Lindgren",
                            TeamId = 12
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2016, 7, 11, 4, 16, 48, 558, DateTimeKind.Utc).AddTicks(4391),
                            Deadline = new DateTime(3978, 5, 8, 10, 45, 7, 296, DateTimeKind.Utc).AddTicks(8124),
                            Description = "Laudantium qui sed dolor voluptatibus quia facere.",
                            Name = "Carmel O'Reilly",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 13,
                            CreatedAt = new DateTime(2018, 3, 18, 9, 10, 45, 541, DateTimeKind.Utc).AddTicks(9109),
                            Deadline = new DateTime(3854, 3, 13, 9, 49, 54, 594, DateTimeKind.Utc).AddTicks(8492),
                            Description = "Est et optio illo reiciendis illo alias numquam vitae dolores. Illum aspernatur veritatis quia dolores repellat. Eius sed doloribus nostrum eaque pariatur.",
                            Name = "Zella Roob",
                            TeamId = 13
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 16,
                            CreatedAt = new DateTime(2013, 12, 17, 17, 40, 37, 340, DateTimeKind.Utc).AddTicks(2710),
                            Deadline = new DateTime(8445, 8, 7, 3, 32, 5, 299, DateTimeKind.Utc).AddTicks(1030),
                            Description = "Alias sequi non tenetur possimus ullam qui sint laboriosam.",
                            Name = "Felipa Mosciski",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 12,
                            CreatedAt = new DateTime(2022, 9, 13, 0, 45, 41, 961, DateTimeKind.Utc).AddTicks(7982),
                            Deadline = new DateTime(6316, 6, 5, 11, 11, 11, 374, DateTimeKind.Utc).AddTicks(7063),
                            Description = "Non et omnis error veritatis tenetur corrupti laborum commodi voluptatem. Autem eaque quod in necessitatibus adipisci. Ipsa eos quod tempore vel suscipit. Est illo praesentium aliquam sed beatae et tempore aut voluptate. Vitae facilis nihil.",
                            Name = "Lauretta Fay",
                            TeamId = 20
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 17,
                            CreatedAt = new DateTime(2019, 1, 18, 8, 33, 37, 387, DateTimeKind.Utc).AddTicks(4740),
                            Deadline = new DateTime(2372, 5, 6, 19, 37, 3, 192, DateTimeKind.Utc).AddTicks(5873),
                            Description = "Provident aut error velit libero odio corrupti alias nisi.\nEt nostrum doloremque qui quo.\nMinima qui illum harum officia magnam maiores qui.\nQui iure occaecati velit eum corrupti est id enim et.\nAdipisci maxime amet asperiores eos animi.\nIncidunt voluptatum aut.",
                            Name = "Geovany Hackett",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 4,
                            CreatedAt = new DateTime(2022, 10, 21, 18, 19, 16, 730, DateTimeKind.Utc).AddTicks(3333),
                            Deadline = new DateTime(3137, 1, 24, 3, 32, 54, 680, DateTimeKind.Utc).AddTicks(8897),
                            Description = "exercitationem",
                            Name = "Broderick Douglas",
                            TeamId = 14
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 9,
                            CreatedAt = new DateTime(2019, 4, 21, 17, 54, 58, 883, DateTimeKind.Utc).AddTicks(8348),
                            Deadline = new DateTime(3732, 2, 10, 7, 10, 4, 289, DateTimeKind.Utc).AddTicks(2788),
                            Description = "Harum corrupti nemo et laudantium. Nulla sed illum ratione itaque ratione assumenda. Corporis sapiente reiciendis hic architecto soluta quis accusantium nesciunt recusandae.",
                            Name = "Beulah Hayes",
                            TeamId = 9
                        });
                });

            modelBuilder.Entity("BASTask.DAL.Entities.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerformerId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerformerId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 2, 22, 3, 31, 7, 63, DateTimeKind.Utc).AddTicks(1909),
                            Description = "Rerum quia libero rerum iste quibusdam optio optio.",
                            FinishedAt = new DateTime(7109, 10, 29, 4, 15, 25, 833, DateTimeKind.Utc).AddTicks(4129),
                            Name = "Anika Smith",
                            PerformerId = 5,
                            ProjectId = 9,
                            State = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 3, 29, 6, 7, 34, 524, DateTimeKind.Utc).AddTicks(8329),
                            Description = "laudantium",
                            FinishedAt = new DateTime(8337, 5, 28, 20, 37, 45, 379, DateTimeKind.Utc).AddTicks(8294),
                            Name = "Grace Reichel",
                            PerformerId = 3,
                            ProjectId = 10,
                            State = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2014, 2, 24, 14, 38, 17, 750, DateTimeKind.Utc).AddTicks(4185),
                            Description = "Sapiente nihil quae dolorem reiciendis.\nUt a repellat aut dolor quia harum ullam non.\nPorro voluptas alias sint.",
                            FinishedAt = new DateTime(8505, 7, 16, 0, 42, 37, 77, DateTimeKind.Utc).AddTicks(5190),
                            Name = "Maria Powlowski",
                            PerformerId = 2,
                            ProjectId = 3,
                            State = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 6, 30, 2, 23, 44, 121, DateTimeKind.Utc).AddTicks(1651),
                            Description = "rerum",
                            FinishedAt = new DateTime(2666, 11, 11, 10, 36, 39, 9, DateTimeKind.Utc).AddTicks(9742),
                            Name = "Lonzo Jast",
                            PerformerId = 9,
                            ProjectId = 15,
                            State = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2017, 6, 29, 21, 56, 47, 825, DateTimeKind.Utc).AddTicks(4012),
                            Description = "Nostrum nihil sit eveniet id.\nAut cum sint enim enim voluptatem.\nDoloribus et qui ab quae minima qui animi.\nOccaecati dolorem minus consequuntur deleniti qui est dolores.\nConsequatur omnis et.",
                            FinishedAt = new DateTime(7477, 8, 3, 7, 7, 35, 942, DateTimeKind.Utc).AddTicks(5771),
                            Name = "Sarah Reynolds",
                            PerformerId = 17,
                            ProjectId = 8,
                            State = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 12, 1, 23, 29, 33, 485, DateTimeKind.Utc).AddTicks(2956),
                            Description = "quis",
                            FinishedAt = new DateTime(8854, 5, 4, 14, 8, 30, 147, DateTimeKind.Utc).AddTicks(838),
                            Name = "Clarissa Parisian",
                            PerformerId = 1,
                            ProjectId = 1,
                            State = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 4, 1, 10, 59, 25, 40, DateTimeKind.Utc).AddTicks(3346),
                            Description = "Suscipit officia pariatur unde aliquid.\nEsse recusandae fugit mollitia minus accusantium nemo neque.\nVoluptas ex omnis esse aperiam.\nNihil consequatur dolorem ut ut id enim saepe sint architecto.\nDoloribus ut odit fugiat non eos aliquid optio molestiae quia.",
                            FinishedAt = new DateTime(8628, 3, 25, 3, 12, 13, 618, DateTimeKind.Utc).AddTicks(7000),
                            Name = "Clifton Torphy",
                            PerformerId = 17,
                            ProjectId = 19,
                            State = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2017, 11, 13, 2, 58, 45, 29, DateTimeKind.Utc).AddTicks(3033),
                            Description = "Consequatur quo sunt incidunt velit et voluptatibus eum nobis ab. Perferendis dolorem nobis officiis eius eum. Velit similique expedita ea blanditiis corrupti. Aut vero dolores quam voluptatum voluptas ipsa pariatur tempora velit. Doloremque consequuntur aut et.",
                            FinishedAt = new DateTime(7042, 10, 22, 4, 29, 22, 739, DateTimeKind.Utc).AddTicks(4004),
                            Name = "Lonnie Dare",
                            PerformerId = 17,
                            ProjectId = 5,
                            State = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2013, 12, 1, 5, 46, 2, 200, DateTimeKind.Utc).AddTicks(3109),
                            Description = "Quasi rerum aspernatur id.",
                            FinishedAt = new DateTime(9238, 4, 9, 0, 46, 23, 414, DateTimeKind.Utc).AddTicks(7893),
                            Name = "Nicolette Jast",
                            PerformerId = 17,
                            ProjectId = 6,
                            State = 0
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2014, 9, 8, 5, 21, 43, 575, DateTimeKind.Utc).AddTicks(9742),
                            Description = "Iusto dolore expedita sit harum molestiae sapiente error vel. Beatae totam incidunt eum. Molestiae voluptatum harum. Aliquid assumenda ullam quaerat veniam at sed aut. Natus et eos voluptates qui saepe. Et rerum ea sit occaecati sunt voluptatem tempore numquam excepturi.",
                            FinishedAt = new DateTime(3946, 4, 6, 16, 35, 46, 549, DateTimeKind.Utc).AddTicks(9634),
                            Name = "Urban Okuneva",
                            PerformerId = 8,
                            ProjectId = 8,
                            State = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2014, 6, 16, 23, 29, 52, 357, DateTimeKind.Utc).AddTicks(2260),
                            Description = "Quos accusantium est qui ullam ut culpa sunt.\nLibero sunt omnis assumenda ad doloribus.\nDolores voluptatibus corporis eos qui molestias.",
                            FinishedAt = new DateTime(8614, 3, 14, 3, 33, 21, 369, DateTimeKind.Utc).AddTicks(6849),
                            Name = "Devin Johnson",
                            PerformerId = 15,
                            ProjectId = 1,
                            State = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2020, 10, 25, 17, 35, 12, 682, DateTimeKind.Utc).AddTicks(7118),
                            Description = "dolores",
                            FinishedAt = new DateTime(2847, 1, 21, 11, 43, 21, 935, DateTimeKind.Utc).AddTicks(936),
                            Name = "Letitia Fahey",
                            PerformerId = 6,
                            ProjectId = 17,
                            State = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 5, 7, 17, 9, 35, 594, DateTimeKind.Utc).AddTicks(3618),
                            Description = "Alias nesciunt illo eum et cumque. Omnis ipsum reiciendis. Quia vel et doloremque sed pariatur. Magni aut cum dolores. Qui dolorum deleniti cupiditate maiores doloribus.",
                            FinishedAt = new DateTime(9233, 8, 9, 7, 32, 31, 130, DateTimeKind.Utc).AddTicks(8374),
                            Name = "Cary Boyer",
                            PerformerId = 16,
                            ProjectId = 16,
                            State = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 3, 2, 11, 45, 55, 629, DateTimeKind.Utc).AddTicks(4664),
                            Description = "Cum et id laboriosam sed voluptatem dolorum.",
                            FinishedAt = new DateTime(9474, 3, 27, 13, 17, 5, 779, DateTimeKind.Utc).AddTicks(9095),
                            Name = "Marjory Gleason",
                            PerformerId = 7,
                            ProjectId = 17,
                            State = 0
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2017, 10, 16, 23, 26, 27, 273, DateTimeKind.Utc).AddTicks(3732),
                            Description = "Eos assumenda eos aut aut quibusdam autem. Qui delectus quisquam sequi sed et. Suscipit minima est in autem cupiditate adipisci quidem. Incidunt adipisci non. Voluptatibus voluptatem debitis deserunt.",
                            FinishedAt = new DateTime(5061, 1, 10, 15, 29, 41, 532, DateTimeKind.Utc).AddTicks(8702),
                            Name = "Helmer Wintheiser",
                            PerformerId = 20,
                            ProjectId = 20,
                            State = 2
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2015, 6, 7, 15, 48, 24, 914, DateTimeKind.Utc).AddTicks(7884),
                            Description = "Sint praesentium et.\nRepellat et voluptas nesciunt molestiae voluptas.\nDolor reiciendis esse maiores repellat maiores in dolore quo.\nFugiat aut accusamus voluptatem quos et.",
                            FinishedAt = new DateTime(9518, 12, 21, 5, 52, 9, 240, DateTimeKind.Utc).AddTicks(9780),
                            Name = "Devonte Powlowski",
                            PerformerId = 17,
                            ProjectId = 11,
                            State = 0
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2014, 12, 24, 6, 20, 16, 671, DateTimeKind.Utc).AddTicks(9947),
                            Description = "Expedita id sed earum quam eveniet.\nTemporibus aliquam animi ea aspernatur dolorem laborum officia autem.\nEx quo sapiente tempore aspernatur odio quae ut.\nNon totam et ipsa nam accusantium repudiandae.\nCum rerum perferendis quisquam aperiam voluptatibus expedita veniam.\nMaxime consequatur temporibus illo a quidem.",
                            FinishedAt = new DateTime(7549, 5, 15, 10, 13, 45, 265, DateTimeKind.Utc).AddTicks(9448),
                            Name = "Reginald Ferry",
                            PerformerId = 5,
                            ProjectId = 12,
                            State = 0
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2017, 6, 28, 8, 53, 12, 702, DateTimeKind.Utc).AddTicks(6147),
                            Description = "reprehenderit",
                            FinishedAt = new DateTime(5865, 8, 8, 2, 51, 37, 331, DateTimeKind.Utc).AddTicks(2323),
                            Name = "Coralie Pfeffer",
                            PerformerId = 11,
                            ProjectId = 12,
                            State = 2
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 1, 14, 19, 26, 18, 460, DateTimeKind.Utc).AddTicks(2303),
                            Description = "harum",
                            FinishedAt = new DateTime(2418, 12, 20, 0, 2, 54, 911, DateTimeKind.Utc).AddTicks(9662),
                            Name = "Rosina Kilback",
                            PerformerId = 18,
                            ProjectId = 12,
                            State = 2
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2015, 11, 2, 1, 10, 18, 12, DateTimeKind.Utc).AddTicks(5446),
                            Description = "Possimus perferendis expedita fuga iusto perspiciatis quos omnis.",
                            FinishedAt = new DateTime(2065, 6, 10, 13, 24, 43, 874, DateTimeKind.Utc).AddTicks(7888),
                            Name = "Jennings Zemlak",
                            PerformerId = 4,
                            ProjectId = 8,
                            State = 1
                        });
                });

            modelBuilder.Entity("BASTask.DAL.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2016, 10, 4, 7, 44, 0, 313, DateTimeKind.Utc).AddTicks(2711),
                            Name = "Alfreda Gulgowski"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2015, 8, 3, 4, 26, 49, 185, DateTimeKind.Utc).AddTicks(1003),
                            Name = "Fausto Brown"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2017, 12, 9, 3, 41, 36, 905, DateTimeKind.Utc).AddTicks(2992),
                            Name = "Casimir Quigley"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2016, 11, 13, 23, 46, 43, 4, DateTimeKind.Utc).AddTicks(5832),
                            Name = "Ellen Wyman"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 8, 22, 15, 55, 59, 509, DateTimeKind.Utc).AddTicks(8744),
                            Name = "Mariah Berge"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2017, 3, 12, 10, 43, 44, 73, DateTimeKind.Utc).AddTicks(8908),
                            Name = "Salma Ratke"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 11, 7, 22, 42, 46, 233, DateTimeKind.Utc).AddTicks(9700),
                            Name = "Golda Funk"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2014, 1, 14, 19, 48, 26, 479, DateTimeKind.Utc).AddTicks(4932),
                            Name = "Earlene Gerlach"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 7, 18, 3, 41, 42, 970, DateTimeKind.Utc).AddTicks(2054),
                            Name = "Nils McClure"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 5, 9, 5, 22, 18, 93, DateTimeKind.Utc).AddTicks(5142),
                            Name = "Madaline Bogan"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2013, 10, 10, 10, 11, 49, 55, DateTimeKind.Utc).AddTicks(5880),
                            Name = "Amy Mertz"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2020, 5, 8, 2, 13, 3, 299, DateTimeKind.Utc).AddTicks(3889),
                            Name = "Montana Kuhlman"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 7, 5, 23, 41, 36, 864, DateTimeKind.Utc).AddTicks(4389),
                            Name = "Garrett Lakin"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2018, 1, 26, 19, 7, 43, 917, DateTimeKind.Utc).AddTicks(6527),
                            Name = "Bobby Hartmann"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2017, 4, 4, 4, 12, 48, 111, DateTimeKind.Utc).AddTicks(3162),
                            Name = "Kris Padberg"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 7, 31, 11, 51, 58, 27, DateTimeKind.Utc).AddTicks(3151),
                            Name = "Arnold Casper"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2015, 7, 3, 19, 20, 22, 375, DateTimeKind.Utc).AddTicks(6358),
                            Name = "Diego Sporer"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2015, 4, 23, 20, 56, 43, 247, DateTimeKind.Utc).AddTicks(1939),
                            Name = "Danyka Collins"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 12, 31, 2, 0, 10, 631, DateTimeKind.Utc).AddTicks(8142),
                            Name = "Sherwood Hartmann"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2014, 2, 8, 13, 12, 58, 134, DateTimeKind.Utc).AddTicks(3590),
                            Name = "Mathias Bernhard"
                        });
                });

            modelBuilder.Entity("BASTask.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDay = new DateTime(1994, 12, 11, 3, 53, 31, 415, DateTimeKind.Utc).AddTicks(9651),
                            Email = "Sophia.Sporer30@gmail.com",
                            FirstName = "Marcelina",
                            LastName = "Dare",
                            RegisteredAt = new DateTime(2019, 1, 3, 6, 12, 34, 502, DateTimeKind.Utc).AddTicks(5614),
                            TeamId = 17
                        },
                        new
                        {
                            Id = 2,
                            BirthDay = new DateTime(2001, 6, 6, 4, 1, 43, 310, DateTimeKind.Utc).AddTicks(9463),
                            Email = "Ollie_Torphy42@yahoo.com",
                            FirstName = "Marques",
                            LastName = "Schmitt",
                            RegisteredAt = new DateTime(2022, 5, 17, 15, 26, 47, 638, DateTimeKind.Utc).AddTicks(1631),
                            TeamId = 5
                        },
                        new
                        {
                            Id = 3,
                            BirthDay = new DateTime(2014, 10, 12, 0, 3, 46, 286, DateTimeKind.Utc).AddTicks(2699),
                            Email = "Dayna.Connelly1@gmail.com",
                            FirstName = "Cristal",
                            LastName = "Reinger",
                            RegisteredAt = new DateTime(2015, 7, 20, 2, 51, 59, 605, DateTimeKind.Utc).AddTicks(6551),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            BirthDay = new DateTime(2015, 4, 3, 6, 34, 32, 715, DateTimeKind.Utc).AddTicks(7275),
                            Email = "Makayla_Dibbert@gmail.com",
                            FirstName = "Bo",
                            LastName = "Bogan",
                            RegisteredAt = new DateTime(2021, 4, 18, 17, 52, 47, 417, DateTimeKind.Utc).AddTicks(3252),
                            TeamId = 5
                        },
                        new
                        {
                            Id = 5,
                            BirthDay = new DateTime(1996, 1, 10, 21, 52, 44, 947, DateTimeKind.Utc).AddTicks(7889),
                            Email = "Raphaelle.Flatley@hotmail.com",
                            FirstName = "Evalyn",
                            LastName = "DuBuque",
                            RegisteredAt = new DateTime(2017, 5, 4, 11, 9, 28, 85, DateTimeKind.Utc).AddTicks(5541),
                            TeamId = 4
                        },
                        new
                        {
                            Id = 6,
                            BirthDay = new DateTime(2012, 10, 29, 22, 56, 14, 843, DateTimeKind.Utc).AddTicks(3789),
                            Email = "Shaylee63@yahoo.com",
                            FirstName = "Jerod",
                            LastName = "Kemmer",
                            RegisteredAt = new DateTime(2019, 3, 18, 2, 13, 37, 325, DateTimeKind.Utc).AddTicks(4805),
                            TeamId = 6
                        },
                        new
                        {
                            Id = 7,
                            BirthDay = new DateTime(2003, 3, 12, 2, 11, 13, 538, DateTimeKind.Utc).AddTicks(5808),
                            Email = "Orrin71@gmail.com",
                            FirstName = "Lola",
                            LastName = "Barrows",
                            RegisteredAt = new DateTime(2023, 1, 11, 15, 2, 18, 678, DateTimeKind.Utc).AddTicks(6042),
                            TeamId = 12
                        },
                        new
                        {
                            Id = 8,
                            BirthDay = new DateTime(2003, 3, 31, 22, 24, 58, 557, DateTimeKind.Utc).AddTicks(5481),
                            Email = "Andreane_Stark@gmail.com",
                            FirstName = "Sophia",
                            LastName = "Bogisich",
                            RegisteredAt = new DateTime(2019, 3, 10, 3, 12, 17, 117, DateTimeKind.Utc).AddTicks(5669),
                            TeamId = 6
                        },
                        new
                        {
                            Id = 9,
                            BirthDay = new DateTime(2018, 2, 3, 21, 10, 36, 453, DateTimeKind.Utc).AddTicks(8277),
                            Email = "Deon_Kunde@hotmail.com",
                            FirstName = "Evelyn",
                            LastName = "Vandervort",
                            RegisteredAt = new DateTime(2020, 2, 10, 20, 16, 35, 309, DateTimeKind.Utc).AddTicks(3265),
                            TeamId = 13
                        },
                        new
                        {
                            Id = 10,
                            BirthDay = new DateTime(2000, 11, 19, 13, 44, 26, 497, DateTimeKind.Utc).AddTicks(3508),
                            Email = "Cortney_OKon22@gmail.com",
                            FirstName = "Otha",
                            LastName = "Lemke",
                            RegisteredAt = new DateTime(2017, 2, 10, 7, 23, 36, 439, DateTimeKind.Utc).AddTicks(9673),
                            TeamId = 6
                        },
                        new
                        {
                            Id = 11,
                            BirthDay = new DateTime(2016, 3, 10, 9, 26, 47, 872, DateTimeKind.Utc).AddTicks(2869),
                            Email = "Naomie4@hotmail.com",
                            FirstName = "Letitia",
                            LastName = "Kshlerin",
                            RegisteredAt = new DateTime(2019, 7, 7, 2, 39, 42, 884, DateTimeKind.Utc).AddTicks(9792),
                            TeamId = 3
                        },
                        new
                        {
                            Id = 12,
                            BirthDay = new DateTime(2018, 11, 4, 8, 53, 34, 167, DateTimeKind.Utc).AddTicks(201),
                            Email = "Asa75@gmail.com",
                            FirstName = "Faustino",
                            LastName = "Cronin",
                            RegisteredAt = new DateTime(2020, 10, 19, 12, 10, 28, 869, DateTimeKind.Utc).AddTicks(3144),
                            TeamId = 20
                        },
                        new
                        {
                            Id = 13,
                            BirthDay = new DateTime(2011, 7, 6, 23, 8, 38, 906, DateTimeKind.Utc).AddTicks(5416),
                            Email = "Randall.Schneider93@yahoo.com",
                            FirstName = "Jannie",
                            LastName = "Willms",
                            RegisteredAt = new DateTime(2014, 10, 11, 10, 13, 31, 351, DateTimeKind.Utc).AddTicks(6967),
                            TeamId = 13
                        },
                        new
                        {
                            Id = 14,
                            BirthDay = new DateTime(2008, 10, 18, 2, 5, 24, 118, DateTimeKind.Utc).AddTicks(835),
                            Email = "Haskell37@hotmail.com",
                            FirstName = "Rosie",
                            LastName = "Huel",
                            RegisteredAt = new DateTime(2017, 8, 10, 21, 17, 0, 730, DateTimeKind.Utc).AddTicks(9119),
                            TeamId = 15
                        },
                        new
                        {
                            Id = 15,
                            BirthDay = new DateTime(2023, 6, 22, 23, 18, 44, 422, DateTimeKind.Utc).AddTicks(2066),
                            Email = "Blaze.Carroll@hotmail.com",
                            FirstName = "Tyler",
                            LastName = "Berge",
                            RegisteredAt = new DateTime(2018, 1, 6, 22, 25, 23, 56, DateTimeKind.Utc).AddTicks(6405),
                            TeamId = 14
                        },
                        new
                        {
                            Id = 16,
                            BirthDay = new DateTime(2013, 5, 2, 13, 17, 16, 97, DateTimeKind.Utc).AddTicks(8987),
                            Email = "Raul.Haley47@yahoo.com",
                            FirstName = "Kimberly",
                            LastName = "Prosacco",
                            RegisteredAt = new DateTime(2022, 11, 18, 18, 4, 56, 993, DateTimeKind.Utc).AddTicks(6328),
                            TeamId = 18
                        },
                        new
                        {
                            Id = 17,
                            BirthDay = new DateTime(2004, 11, 28, 9, 59, 37, 103, DateTimeKind.Utc).AddTicks(876),
                            Email = "Dorian73@gmail.com",
                            FirstName = "Rita",
                            LastName = "Aufderhar",
                            RegisteredAt = new DateTime(2021, 10, 11, 7, 53, 5, 315, DateTimeKind.Utc).AddTicks(5317),
                            TeamId = 3
                        },
                        new
                        {
                            Id = 18,
                            BirthDay = new DateTime(2004, 2, 18, 10, 20, 0, 581, DateTimeKind.Utc).AddTicks(5370),
                            Email = "Jamel.Bednar@gmail.com",
                            FirstName = "Reginald",
                            LastName = "Haag",
                            RegisteredAt = new DateTime(2020, 9, 1, 16, 31, 12, 44, DateTimeKind.Utc).AddTicks(7441),
                            TeamId = 16
                        },
                        new
                        {
                            Id = 19,
                            BirthDay = new DateTime(2019, 5, 24, 16, 42, 8, 452, DateTimeKind.Utc).AddTicks(8326),
                            Email = "Liliane87@yahoo.com",
                            FirstName = "Callie",
                            LastName = "Robel",
                            RegisteredAt = new DateTime(2022, 10, 9, 23, 19, 32, 947, DateTimeKind.Utc).AddTicks(8502),
                            TeamId = 3
                        },
                        new
                        {
                            Id = 20,
                            BirthDay = new DateTime(1993, 11, 20, 21, 55, 9, 942, DateTimeKind.Utc).AddTicks(6076),
                            Email = "Dorothy.Corkery@hotmail.com",
                            FirstName = "Elvera",
                            LastName = "McCullough",
                            RegisteredAt = new DateTime(2013, 9, 23, 21, 43, 33, 854, DateTimeKind.Utc).AddTicks(3896),
                            TeamId = 8
                        });
                });

            modelBuilder.Entity("BASTask.DAL.Entities.Project", b =>
                {
                    b.HasOne("BASTask.DAL.Entities.Team", "Team")
                        .WithMany("Projects")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BASTask.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BASTask.DAL.Entities.Task", b =>
                {
                    b.HasOne("BASTask.DAL.Entities.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BASTask.DAL.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BASTask.DAL.Entities.User", b =>
                {
                    b.HasOne("BASTask.DAL.Entities.Team", "Team")
                        .WithMany("Users")
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BASTask.DAL.Entities.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("BASTask.DAL.Entities.Team", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BASTask.DAL.Entities.User", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
