// <auto-generated />
using System;
using BSATask.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BSATask.DAL.Migrations
{
    [DbContext(typeof(BSATaskContext))]
    partial class BSATaskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BASTask.DAL.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TeamId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 9,
                            CreatedAt = new DateTime(2020, 7, 14, 5, 46, 52, 130, DateTimeKind.Utc).AddTicks(887),
                            Deadline = new DateTime(7888, 7, 9, 22, 17, 44, 652, DateTimeKind.Utc).AddTicks(9309),
                            Description = "ullam",
                            Name = "Francisca Schaefer",
                            TeamId = 16
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2014, 6, 8, 21, 26, 47, 485, DateTimeKind.Utc).AddTicks(7928),
                            Deadline = new DateTime(5260, 7, 23, 20, 11, 44, 426, DateTimeKind.Utc).AddTicks(5263),
                            Description = "Aut repellendus nihil iusto qui distinctio necessitatibus.\nConsectetur unde velit blanditiis repellat dolores minima.\nAd et qui dicta.",
                            Name = "Ladarius Hane",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 8,
                            CreatedAt = new DateTime(2019, 12, 10, 13, 27, 10, 831, DateTimeKind.Utc).AddTicks(4863),
                            Deadline = new DateTime(6700, 3, 26, 21, 43, 52, 359, DateTimeKind.Utc).AddTicks(7654),
                            Description = "Sequi nostrum fugit.",
                            Name = "Arjun Langosh",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 13,
                            CreatedAt = new DateTime(2018, 12, 29, 6, 4, 56, 469, DateTimeKind.Utc).AddTicks(6452),
                            Deadline = new DateTime(6602, 6, 28, 2, 32, 39, 44, DateTimeKind.Utc).AddTicks(8507),
                            Description = "Harum in amet deleniti. Maiores expedita alias consectetur est et. Aut provident quae ea temporibus assumenda ratione consectetur repudiandae. Sed blanditiis aut beatae nulla mollitia.",
                            Name = "Queenie Moen",
                            TeamId = 11
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 19,
                            CreatedAt = new DateTime(2017, 7, 9, 20, 10, 46, 325, DateTimeKind.Utc).AddTicks(8384),
                            Deadline = new DateTime(6698, 11, 5, 10, 45, 0, 536, DateTimeKind.Utc).AddTicks(5563),
                            Description = "Ea similique natus similique perferendis assumenda voluptas adipisci. Quos eos minima quasi doloribus optio. Modi quia suscipit quas qui reiciendis.",
                            Name = "Reina Johns",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 19,
                            CreatedAt = new DateTime(2022, 2, 22, 12, 25, 34, 910, DateTimeKind.Utc).AddTicks(6005),
                            Deadline = new DateTime(2890, 8, 30, 13, 1, 12, 580, DateTimeKind.Utc).AddTicks(9393),
                            Description = "Similique deleniti ullam.\nOmnis error sit eum et quibusdam suscipit atque.\nQuas omnis et officia ipsa esse.\nEos voluptates dolores mollitia esse consequuntur sint cum nostrum voluptatem.",
                            Name = "Elliott Graham",
                            TeamId = 18
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 12,
                            CreatedAt = new DateTime(2018, 5, 5, 9, 45, 45, 844, DateTimeKind.Utc).AddTicks(4883),
                            Deadline = new DateTime(5815, 6, 6, 18, 18, 10, 317, DateTimeKind.Utc).AddTicks(3176),
                            Description = "Neque at omnis nam dolore ipsum dicta dolorem eos.\nOmnis similique ut id eos rerum.",
                            Name = "Torey Witting",
                            TeamId = 19
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 18,
                            CreatedAt = new DateTime(2014, 12, 19, 22, 48, 46, 755, DateTimeKind.Utc).AddTicks(1977),
                            Deadline = new DateTime(3622, 2, 17, 10, 18, 48, 959, DateTimeKind.Utc).AddTicks(854),
                            Description = "aut",
                            Name = "Daryl Effertz",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 12,
                            CreatedAt = new DateTime(2016, 11, 28, 10, 52, 54, 40, DateTimeKind.Utc).AddTicks(8555),
                            Deadline = new DateTime(4235, 3, 13, 19, 14, 2, 348, DateTimeKind.Utc).AddTicks(4869),
                            Description = "Perferendis repellendus aliquid aspernatur reiciendis. Labore iste facilis tempore et. Autem et nam qui nemo repellat consequatur placeat est ipsum. Repellat nisi temporibus facere. Saepe possimus et in reprehenderit et sequi.",
                            Name = "Heather Abbott",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 9,
                            CreatedAt = new DateTime(2015, 8, 17, 7, 46, 13, 787, DateTimeKind.Utc).AddTicks(5874),
                            Deadline = new DateTime(4405, 3, 20, 10, 35, 37, 323, DateTimeKind.Utc).AddTicks(6482),
                            Description = "Doloribus aperiam aliquid veritatis et culpa qui dolores dicta unde.",
                            Name = "Dino Tremblay",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 20,
                            CreatedAt = new DateTime(2015, 12, 23, 10, 0, 32, 211, DateTimeKind.Utc).AddTicks(2929),
                            Deadline = new DateTime(5645, 10, 1, 0, 23, 37, 196, DateTimeKind.Utc).AddTicks(8059),
                            Description = "Perferendis explicabo veritatis architecto facere aut dolorem.\nDeleniti eum temporibus ipsam itaque.",
                            Name = "Birdie Bayer",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 10,
                            CreatedAt = new DateTime(2020, 1, 1, 2, 20, 37, 254, DateTimeKind.Utc).AddTicks(3735),
                            Deadline = new DateTime(6685, 7, 2, 13, 54, 34, 960, DateTimeKind.Utc).AddTicks(7600),
                            Description = "Deserunt atque minus.",
                            Name = "Griffin Hamill",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 7,
                            CreatedAt = new DateTime(2020, 1, 21, 14, 47, 4, 279, DateTimeKind.Utc).AddTicks(6038),
                            Deadline = new DateTime(3078, 5, 26, 4, 47, 14, 554, DateTimeKind.Utc).AddTicks(3991),
                            Description = "Sequi nemo blanditiis veniam autem quis veniam id quas.",
                            Name = "Myrtle Reynolds",
                            TeamId = 18
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 13,
                            CreatedAt = new DateTime(2020, 3, 31, 4, 48, 16, 616, DateTimeKind.Utc).AddTicks(2515),
                            Deadline = new DateTime(8822, 6, 21, 21, 14, 54, 511, DateTimeKind.Utc).AddTicks(2767),
                            Description = "Molestias voluptate ex ipsa est quia. Unde similique ab voluptas. Eum vel neque omnis est omnis aut. Porro velit tenetur illum accusantium ut. Laudantium non qui nemo fugit possimus.",
                            Name = "Jerrold Abbott",
                            TeamId = 12
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 4,
                            CreatedAt = new DateTime(2017, 5, 20, 1, 6, 47, 156, DateTimeKind.Utc).AddTicks(9958),
                            Deadline = new DateTime(3978, 1, 23, 14, 47, 55, 327, DateTimeKind.Utc).AddTicks(4385),
                            Description = "nobis",
                            Name = "Karli Donnelly",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 11,
                            CreatedAt = new DateTime(2020, 3, 16, 2, 1, 9, 162, DateTimeKind.Utc).AddTicks(1767),
                            Deadline = new DateTime(6205, 4, 13, 12, 31, 33, 837, DateTimeKind.Utc).AddTicks(9223),
                            Description = "Culpa consectetur ut dolorem velit dolore non omnis voluptates est.\nRepudiandae quia quo nam.\nEos possimus eos.",
                            Name = "Antwan McDermott",
                            TeamId = 14
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 14,
                            CreatedAt = new DateTime(2013, 9, 3, 18, 40, 10, 660, DateTimeKind.Utc).AddTicks(4225),
                            Deadline = new DateTime(5373, 2, 3, 17, 26, 35, 604, DateTimeKind.Utc).AddTicks(9821),
                            Description = "at",
                            Name = "Eliza Rohan",
                            TeamId = 20
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 5,
                            CreatedAt = new DateTime(2016, 4, 14, 18, 44, 2, 771, DateTimeKind.Utc).AddTicks(2940),
                            Deadline = new DateTime(3936, 2, 12, 10, 36, 7, 773, DateTimeKind.Utc).AddTicks(9408),
                            Description = "non",
                            Name = "Verlie Pollich",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 11,
                            CreatedAt = new DateTime(2022, 11, 6, 10, 20, 45, 375, DateTimeKind.Utc).AddTicks(7400),
                            Deadline = new DateTime(6233, 9, 29, 13, 58, 4, 135, DateTimeKind.Utc).AddTicks(1632),
                            Description = "minima",
                            Name = "Maude Beahan",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 14,
                            CreatedAt = new DateTime(2015, 6, 11, 19, 23, 16, 43, DateTimeKind.Utc).AddTicks(36),
                            Deadline = new DateTime(7990, 7, 25, 15, 55, 29, 702, DateTimeKind.Utc).AddTicks(9276),
                            Description = "Explicabo rerum dolorem debitis aut fuga provident nesciunt aut.\nCum exercitationem corporis aspernatur aut sapiente.\nEnim voluptatem laboriosam sit error commodi occaecati quo.\nPariatur id quo.\nPerspiciatis eius atque explicabo cum.\nNeque est qui aut quaerat nam libero amet rerum quia.",
                            Name = "Jonas Fadel",
                            TeamId = 16
                        });
                });

            modelBuilder.Entity("BASTask.DAL.Entities.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerformerId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerformerId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 3, 30, 15, 7, 44, 271, DateTimeKind.Utc).AddTicks(4827),
                            Description = "Voluptatem aut quas ipsum et provident vero voluptatem.\nDolorem excepturi fugiat.\nMollitia ad occaecati.",
                            FinishedAt = new DateTime(4516, 4, 4, 20, 9, 55, 996, DateTimeKind.Utc).AddTicks(3159),
                            Name = "Eleanore Treutel",
                            PerformerId = 15,
                            ProjectId = 4,
                            State = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2015, 4, 15, 11, 26, 12, 726, DateTimeKind.Utc).AddTicks(8441),
                            Description = "Soluta doloribus rerum molestiae deserunt ad ea tempore.\nItaque doloribus et cumque sunt.",
                            FinishedAt = new DateTime(2179, 9, 28, 21, 47, 51, 537, DateTimeKind.Utc).AddTicks(7407),
                            Name = "Efren Morissette",
                            PerformerId = 15,
                            ProjectId = 15,
                            State = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 6, 26, 14, 39, 51, 705, DateTimeKind.Utc).AddTicks(7374),
                            Description = "Aut molestias fuga veniam ratione tempore esse nulla nesciunt illum. Pariatur explicabo possimus hic eius quo hic quas. Mollitia in illo non non quasi. Sequi fuga deserunt dolor dolores quasi iusto necessitatibus.",
                            FinishedAt = new DateTime(2264, 11, 20, 3, 15, 46, 795, DateTimeKind.Utc).AddTicks(4011),
                            Name = "Eldora Trantow",
                            PerformerId = 5,
                            ProjectId = 18,
                            State = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2018, 9, 21, 15, 35, 47, 775, DateTimeKind.Utc).AddTicks(1624),
                            Description = "Corporis itaque unde rerum rerum enim et veritatis aperiam iusto.\nSaepe est omnis explicabo et a.",
                            FinishedAt = new DateTime(4151, 12, 20, 18, 24, 18, 205, DateTimeKind.Utc).AddTicks(8281),
                            Name = "Humberto McDermott",
                            PerformerId = 19,
                            ProjectId = 13,
                            State = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 3, 25, 20, 41, 3, 635, DateTimeKind.Utc).AddTicks(7362),
                            Description = "neque",
                            FinishedAt = new DateTime(3078, 4, 7, 7, 24, 15, 580, DateTimeKind.Utc).AddTicks(4730),
                            Name = "Porter Hodkiewicz",
                            PerformerId = 16,
                            ProjectId = 17,
                            State = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 12, 29, 1, 30, 59, 449, DateTimeKind.Utc).AddTicks(8349),
                            Description = "Quaerat quia dolores dignissimos sunt doloribus sint odit velit.\nQuasi magnam est voluptate.\nUllam modi animi mollitia accusantium fugit ipsa aut exercitationem.\nSaepe suscipit ducimus autem repudiandae necessitatibus ex eum.",
                            FinishedAt = new DateTime(3711, 4, 10, 19, 19, 15, 422, DateTimeKind.Utc).AddTicks(5461),
                            Name = "Eliza Bradtke",
                            PerformerId = 15,
                            ProjectId = 5,
                            State = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 3, 4, 17, 27, 17, 979, DateTimeKind.Utc).AddTicks(3710),
                            Description = "nam",
                            FinishedAt = new DateTime(5165, 11, 25, 9, 44, 30, 300, DateTimeKind.Utc).AddTicks(8649),
                            Name = "Jocelyn Hamill",
                            PerformerId = 3,
                            ProjectId = 15,
                            State = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 2, 22, 8, 29, 53, 857, DateTimeKind.Utc).AddTicks(3269),
                            Description = "Optio natus nihil repellat. Ut iusto vel. Molestias ipsum architecto. Consequuntur vel amet ipsam in facere. Suscipit molestias voluptatibus.",
                            FinishedAt = new DateTime(9657, 6, 26, 9, 30, 4, 660, DateTimeKind.Utc).AddTicks(2216),
                            Name = "Retta Reichert",
                            PerformerId = 9,
                            ProjectId = 6,
                            State = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2017, 1, 20, 23, 49, 56, 538, DateTimeKind.Utc).AddTicks(670),
                            Description = "Qui nulla quo rerum ut voluptas nemo. Veniam possimus excepturi qui nulla cum aliquam ut aut. Quibusdam illo commodi rerum et non voluptatibus. Voluptas odio itaque et iure in exercitationem vel autem perspiciatis. Doloribus dicta quod sunt ex ut et.",
                            FinishedAt = new DateTime(9886, 9, 18, 19, 8, 57, 719, DateTimeKind.Utc).AddTicks(1819),
                            Name = "Melvina Reynolds",
                            PerformerId = 8,
                            ProjectId = 2,
                            State = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 6, 30, 14, 47, 4, 642, DateTimeKind.Utc).AddTicks(9199),
                            Description = "odio",
                            FinishedAt = new DateTime(7772, 1, 27, 2, 55, 56, 209, DateTimeKind.Utc).AddTicks(7141),
                            Name = "Naomie Monahan",
                            PerformerId = 20,
                            ProjectId = 4,
                            State = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2016, 9, 13, 1, 33, 17, 392, DateTimeKind.Utc).AddTicks(3049),
                            Description = "Nesciunt sequi aliquam aut ea enim est et vitae et.",
                            FinishedAt = new DateTime(7941, 7, 16, 6, 6, 51, 313, DateTimeKind.Utc).AddTicks(670),
                            Name = "Marilie Veum",
                            PerformerId = 8,
                            ProjectId = 1,
                            State = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2013, 7, 24, 23, 56, 36, 688, DateTimeKind.Utc).AddTicks(1127),
                            Description = "Perferendis dolorum vero.",
                            FinishedAt = new DateTime(2484, 9, 26, 8, 49, 31, 625, DateTimeKind.Utc).AddTicks(8174),
                            Name = "Lucienne Fay",
                            PerformerId = 18,
                            ProjectId = 18,
                            State = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2020, 2, 17, 15, 50, 51, 861, DateTimeKind.Utc).AddTicks(8462),
                            Description = "Iure dolorem reprehenderit quas similique voluptatem.\nNihil eos sed voluptatibus nam illum distinctio consequatur sequi autem.",
                            FinishedAt = new DateTime(8678, 9, 16, 13, 54, 43, 429, DateTimeKind.Utc).AddTicks(2692),
                            Name = "Selmer Murray",
                            PerformerId = 2,
                            ProjectId = 12,
                            State = 0
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2020, 9, 24, 18, 22, 7, 197, DateTimeKind.Utc).AddTicks(1726),
                            Description = "Perferendis consequatur rerum sit laborum cumque aut ex hic voluptatem.\nPorro non ut.\nEt blanditiis nostrum.\nAut molestias ut tempore vitae qui perferendis itaque sed.",
                            FinishedAt = new DateTime(7805, 7, 11, 1, 17, 48, 540, DateTimeKind.Utc).AddTicks(8251),
                            Name = "Unique Strosin",
                            PerformerId = 13,
                            ProjectId = 4,
                            State = 0
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2014, 5, 30, 15, 3, 52, 54, DateTimeKind.Utc).AddTicks(9041),
                            Description = "Eos expedita cupiditate placeat omnis odio aut harum iure.",
                            FinishedAt = new DateTime(5180, 9, 2, 8, 21, 7, 917, DateTimeKind.Utc).AddTicks(4787),
                            Name = "Mikayla Balistreri",
                            PerformerId = 4,
                            ProjectId = 17,
                            State = 0
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2016, 7, 15, 6, 18, 53, 536, DateTimeKind.Utc).AddTicks(1801),
                            Description = "Vel facilis rerum asperiores.",
                            FinishedAt = new DateTime(2633, 9, 15, 4, 6, 28, 660, DateTimeKind.Utc).AddTicks(9128),
                            Name = "Samson Buckridge",
                            PerformerId = 19,
                            ProjectId = 13,
                            State = 2
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2017, 6, 8, 16, 17, 32, 131, DateTimeKind.Utc).AddTicks(820),
                            Description = "Ut ea dolore perspiciatis rerum minima asperiores facilis. Consequatur odio accusamus sapiente. Ea aut et dolorum aut. Delectus ea natus.",
                            FinishedAt = new DateTime(9056, 2, 15, 13, 19, 22, 5, DateTimeKind.Utc).AddTicks(9629),
                            Name = "Emily Wehner",
                            PerformerId = 8,
                            ProjectId = 10,
                            State = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 9, 20, 12, 33, 50, 563, DateTimeKind.Utc).AddTicks(14),
                            Description = "Autem qui unde facilis sint veniam impedit. Sit et placeat id repudiandae impedit. Fugiat harum consectetur omnis aspernatur laudantium velit qui sit.",
                            FinishedAt = new DateTime(2197, 8, 9, 10, 3, 20, 820, DateTimeKind.Utc).AddTicks(7297),
                            Name = "Maverick Johnston",
                            PerformerId = 18,
                            ProjectId = 16,
                            State = 0
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2020, 7, 21, 1, 52, 14, 903, DateTimeKind.Utc).AddTicks(5516),
                            Description = "Facere similique aut sed enim. Qui eos et voluptas alias ratione voluptates. Harum veritatis quibusdam labore qui doloremque. Quia ea sit error. Unde aut voluptatum quibusdam qui nam dolore natus pariatur ea. Qui et velit optio dolorum magni nostrum totam.",
                            FinishedAt = new DateTime(4832, 6, 4, 4, 29, 11, 171, DateTimeKind.Utc).AddTicks(1069),
                            Name = "Darrell Abshire",
                            PerformerId = 16,
                            ProjectId = 1,
                            State = 0
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 5, 26, 10, 7, 38, 527, DateTimeKind.Utc).AddTicks(6296),
                            Description = "Nesciunt quisquam laudantium aliquid aut placeat eum.",
                            FinishedAt = new DateTime(7426, 6, 18, 19, 58, 31, 511, DateTimeKind.Utc).AddTicks(1387),
                            Name = "Filiberto Braun",
                            PerformerId = 20,
                            ProjectId = 11,
                            State = 0
                        });
                });

            modelBuilder.Entity("BASTask.DAL.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2015, 11, 20, 3, 14, 6, 31, DateTimeKind.Utc).AddTicks(857),
                            Name = "Jaylon Harber"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2015, 10, 17, 23, 38, 14, 187, DateTimeKind.Utc).AddTicks(8394),
                            Name = "Edison Toy"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 5, 22, 3, 47, 14, 602, DateTimeKind.Utc).AddTicks(534),
                            Name = "Boris Swaniawski"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 11, 17, 7, 44, 16, 111, DateTimeKind.Utc).AddTicks(672),
                            Name = "London Koelpin"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 1, 29, 19, 34, 8, 233, DateTimeKind.Utc).AddTicks(6692),
                            Name = "Felicity Predovic"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2020, 6, 27, 2, 49, 13, 664, DateTimeKind.Utc).AddTicks(1165),
                            Name = "Boris O'Kon"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 4, 1, 20, 36, 57, 215, DateTimeKind.Utc).AddTicks(4159),
                            Name = "Ana Cummerata"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2015, 4, 16, 13, 23, 4, 713, DateTimeKind.Utc).AddTicks(5428),
                            Name = "Gerson Torphy"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2016, 1, 9, 21, 44, 15, 331, DateTimeKind.Utc).AddTicks(4686),
                            Name = "Pearl Wunsch"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 7, 14, 22, 44, 1, 913, DateTimeKind.Utc).AddTicks(190),
                            Name = "Aimee Koelpin"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2014, 8, 13, 10, 42, 10, 927, DateTimeKind.Utc).AddTicks(9352),
                            Name = "Retta Conroy"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2022, 3, 31, 4, 24, 47, 117, DateTimeKind.Utc).AddTicks(4769),
                            Name = "Florencio Funk"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2016, 11, 25, 4, 38, 6, 157, DateTimeKind.Utc).AddTicks(7354),
                            Name = "Efrain Zemlak"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 5, 4, 19, 2, 33, 166, DateTimeKind.Utc).AddTicks(2309),
                            Name = "Madonna Herzog"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2013, 10, 25, 1, 59, 19, 47, DateTimeKind.Utc).AddTicks(7704),
                            Name = "Zachariah Rutherford"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2014, 5, 5, 18, 22, 14, 339, DateTimeKind.Utc).AddTicks(7139),
                            Name = "Allison Hermiston"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2014, 6, 5, 14, 0, 8, 902, DateTimeKind.Utc).AddTicks(3316),
                            Name = "Mike Wunsch"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 1, 8, 21, 56, 42, 472, DateTimeKind.Utc).AddTicks(5567),
                            Name = "Mckenna Kirlin"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 1, 7, 15, 18, 27, 9, DateTimeKind.Utc).AddTicks(2652),
                            Name = "Ignacio Carter"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2013, 11, 21, 15, 3, 14, 658, DateTimeKind.Utc).AddTicks(9359),
                            Name = "Lucy Braun"
                        });
                });

            modelBuilder.Entity("BASTask.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDay = new DateTime(2008, 6, 21, 4, 4, 25, 102, DateTimeKind.Utc).AddTicks(4122),
                            Email = "Lucienne.Heaney@yahoo.com",
                            FirstName = "Nora",
                            LastName = "Altenwerth",
                            RegisteredAt = new DateTime(2017, 12, 18, 11, 24, 30, 646, DateTimeKind.Utc).AddTicks(911),
                            TeamId = 4
                        },
                        new
                        {
                            Id = 2,
                            BirthDay = new DateTime(2013, 5, 21, 13, 1, 11, 461, DateTimeKind.Utc).AddTicks(5338),
                            Email = "Norris.Hoeger@hotmail.com",
                            FirstName = "Dahlia",
                            LastName = "Reynolds",
                            RegisteredAt = new DateTime(2013, 11, 20, 2, 27, 20, 273, DateTimeKind.Utc).AddTicks(1927),
                            TeamId = 6
                        },
                        new
                        {
                            Id = 3,
                            BirthDay = new DateTime(2008, 11, 13, 3, 3, 3, 846, DateTimeKind.Utc).AddTicks(1189),
                            Email = "Rowland99@yahoo.com",
                            FirstName = "Stephania",
                            LastName = "O'Reilly",
                            RegisteredAt = new DateTime(2016, 5, 7, 6, 5, 15, 332, DateTimeKind.Utc).AddTicks(213),
                            TeamId = 18
                        },
                        new
                        {
                            Id = 4,
                            BirthDay = new DateTime(2017, 2, 1, 9, 19, 30, 908, DateTimeKind.Utc).AddTicks(7127),
                            Email = "Josiane_Rempel@gmail.com",
                            FirstName = "Gonzalo",
                            LastName = "Connelly",
                            RegisteredAt = new DateTime(2019, 8, 23, 3, 54, 46, 310, DateTimeKind.Utc).AddTicks(4037),
                            TeamId = 4
                        },
                        new
                        {
                            Id = 5,
                            BirthDay = new DateTime(2021, 12, 12, 0, 28, 40, 51, DateTimeKind.Utc).AddTicks(8643),
                            Email = "Kathlyn_Becker@hotmail.com",
                            FirstName = "Tiara",
                            LastName = "Russel",
                            RegisteredAt = new DateTime(2021, 10, 7, 5, 36, 53, 620, DateTimeKind.Utc).AddTicks(3776),
                            TeamId = 9
                        },
                        new
                        {
                            Id = 6,
                            BirthDay = new DateTime(2008, 4, 18, 18, 11, 14, 773, DateTimeKind.Utc).AddTicks(2920),
                            Email = "Janiya_Mueller@yahoo.com",
                            FirstName = "Jayson",
                            LastName = "Vandervort",
                            RegisteredAt = new DateTime(2013, 10, 7, 14, 56, 5, 469, DateTimeKind.Utc).AddTicks(8368),
                            TeamId = 20
                        },
                        new
                        {
                            Id = 7,
                            BirthDay = new DateTime(2008, 10, 29, 20, 50, 2, 6, DateTimeKind.Utc).AddTicks(7453),
                            Email = "Hector_Little@yahoo.com",
                            FirstName = "Al",
                            LastName = "Kuhlman",
                            RegisteredAt = new DateTime(2023, 1, 29, 6, 37, 25, 756, DateTimeKind.Utc).AddTicks(2913),
                            TeamId = 17
                        },
                        new
                        {
                            Id = 8,
                            BirthDay = new DateTime(2002, 10, 15, 21, 40, 10, 34, DateTimeKind.Utc).AddTicks(7156),
                            Email = "Jo20@gmail.com",
                            FirstName = "Era",
                            LastName = "Marks",
                            RegisteredAt = new DateTime(2019, 7, 27, 12, 30, 6, 94, DateTimeKind.Utc).AddTicks(7777),
                            TeamId = 11
                        },
                        new
                        {
                            Id = 9,
                            BirthDay = new DateTime(2003, 7, 12, 11, 58, 4, 605, DateTimeKind.Utc).AddTicks(9937),
                            Email = "Elsa.Ritchie10@yahoo.com",
                            FirstName = "Presley",
                            LastName = "Hessel",
                            RegisteredAt = new DateTime(2015, 7, 3, 2, 7, 52, 397, DateTimeKind.Utc).AddTicks(7173),
                            TeamId = 11
                        },
                        new
                        {
                            Id = 10,
                            BirthDay = new DateTime(2006, 6, 21, 5, 42, 53, 217, DateTimeKind.Utc).AddTicks(1816),
                            Email = "Candace_Langworth6@yahoo.com",
                            FirstName = "Orval",
                            LastName = "Kunze",
                            RegisteredAt = new DateTime(2022, 5, 24, 1, 6, 3, 764, DateTimeKind.Utc).AddTicks(8884),
                            TeamId = 8
                        },
                        new
                        {
                            Id = 11,
                            BirthDay = new DateTime(1994, 4, 1, 14, 29, 3, 760, DateTimeKind.Utc).AddTicks(9670),
                            Email = "Sherman_Huel@hotmail.com",
                            FirstName = "Sven",
                            LastName = "Quigley",
                            RegisteredAt = new DateTime(2017, 6, 16, 8, 20, 27, 869, DateTimeKind.Utc).AddTicks(155),
                            TeamId = 11
                        },
                        new
                        {
                            Id = 12,
                            BirthDay = new DateTime(2001, 4, 20, 20, 54, 36, 819, DateTimeKind.Utc).AddTicks(5312),
                            Email = "Carrie91@hotmail.com",
                            FirstName = "Audreanne",
                            LastName = "Schinner",
                            RegisteredAt = new DateTime(2019, 10, 19, 14, 43, 22, 867, DateTimeKind.Utc).AddTicks(3727),
                            TeamId = 7
                        },
                        new
                        {
                            Id = 13,
                            BirthDay = new DateTime(2018, 3, 1, 3, 5, 22, 234, DateTimeKind.Utc).AddTicks(6823),
                            Email = "Nicolette.Crona@yahoo.com",
                            FirstName = "Zander",
                            LastName = "Stark",
                            RegisteredAt = new DateTime(2021, 4, 7, 6, 4, 57, 931, DateTimeKind.Utc).AddTicks(3404),
                            TeamId = 6
                        },
                        new
                        {
                            Id = 14,
                            BirthDay = new DateTime(1998, 2, 6, 21, 12, 40, 349, DateTimeKind.Utc).AddTicks(7450),
                            Email = "Vidal_Stanton@hotmail.com",
                            FirstName = "Liana",
                            LastName = "Kuhn",
                            RegisteredAt = new DateTime(2014, 3, 12, 21, 4, 2, 348, DateTimeKind.Utc).AddTicks(4061),
                            TeamId = 15
                        },
                        new
                        {
                            Id = 15,
                            BirthDay = new DateTime(2022, 11, 15, 3, 28, 56, 539, DateTimeKind.Utc).AddTicks(2783),
                            Email = "Mario_Grant69@hotmail.com",
                            FirstName = "Uriel",
                            LastName = "Mante",
                            RegisteredAt = new DateTime(2016, 3, 1, 21, 12, 20, 155, DateTimeKind.Utc).AddTicks(899),
                            TeamId = 14
                        },
                        new
                        {
                            Id = 16,
                            BirthDay = new DateTime(2008, 12, 31, 1, 12, 3, 107, DateTimeKind.Utc).AddTicks(1565),
                            Email = "Celestino_Gibson32@yahoo.com",
                            FirstName = "Narciso",
                            LastName = "Quitzon",
                            RegisteredAt = new DateTime(2018, 4, 25, 8, 2, 28, 557, DateTimeKind.Utc).AddTicks(8157),
                            TeamId = 11
                        },
                        new
                        {
                            Id = 17,
                            BirthDay = new DateTime(2003, 12, 25, 19, 15, 2, 233, DateTimeKind.Utc).AddTicks(1578),
                            Email = "Aubree84@yahoo.com",
                            FirstName = "Dagmar",
                            LastName = "Cummings",
                            RegisteredAt = new DateTime(2022, 2, 7, 19, 18, 32, 371, DateTimeKind.Utc).AddTicks(9055),
                            TeamId = 12
                        },
                        new
                        {
                            Id = 18,
                            BirthDay = new DateTime(2010, 11, 25, 6, 34, 37, 95, DateTimeKind.Utc).AddTicks(967),
                            Email = "Imogene.Schaden@yahoo.com",
                            FirstName = "Ashton",
                            LastName = "Hayes",
                            RegisteredAt = new DateTime(2015, 6, 8, 16, 0, 22, 671, DateTimeKind.Utc).AddTicks(3345),
                            TeamId = 9
                        },
                        new
                        {
                            Id = 19,
                            BirthDay = new DateTime(2018, 5, 13, 21, 27, 48, 73, DateTimeKind.Utc).AddTicks(239),
                            Email = "Carley_Kassulke@yahoo.com",
                            FirstName = "Isidro",
                            LastName = "Kassulke",
                            RegisteredAt = new DateTime(2021, 10, 4, 16, 28, 58, 238, DateTimeKind.Utc).AddTicks(2424),
                            TeamId = 17
                        },
                        new
                        {
                            Id = 20,
                            BirthDay = new DateTime(2000, 11, 9, 4, 59, 43, 96, DateTimeKind.Utc).AddTicks(4852),
                            Email = "Sonny_Rempel@gmail.com",
                            FirstName = "Ova",
                            LastName = "Bartoletti",
                            RegisteredAt = new DateTime(2019, 6, 22, 23, 2, 9, 121, DateTimeKind.Utc).AddTicks(58),
                            TeamId = 3
                        });
                });

            modelBuilder.Entity("BASTask.DAL.Entities.Project", b =>
                {
                    b.HasOne("BASTask.DAL.Entities.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BASTask.DAL.Entities.Team", "Team")
                        .WithMany("Projects")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BASTask.DAL.Entities.Task", b =>
                {
                    b.HasOne("BASTask.DAL.Entities.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BASTask.DAL.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BASTask.DAL.Entities.User", b =>
                {
                    b.HasOne("BASTask.DAL.Entities.Team", "Team")
                        .WithMany("Users")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BASTask.DAL.Entities.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("BASTask.DAL.Entities.Team", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BASTask.DAL.Entities.User", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
